### ISSUE TITLE
nGrinder를 이용한 부하테스트 질문

### ISSUE THREAD

**Issue by hyejungg** [comento-backend-camp/ticket-reservation-server-hyejung#16]
@comento-yun  멘토님! 
Redis를 이용하여 동시성 제어와 관련된 코드를 추가하기 전에 
현재 완성된 코드가 같은 좌석 정보를 서로 다른 유저가 동시에 예약 시 어떤 식으로 저장하는지 확인하고 싶어서 
지난번에 알려주신 코드를 참고하여 다음과 같이 테스트문을 작성했습니다.
```groovy
import HTTPClient.HTTPResponse
import HTTPClient.NVPair
import ch.qos.logback.classic.Level
import net.grinder.plugin.http.HTTPPluginControl
import net.grinder.plugin.http.HTTPRequest
import net.grinder.script.GTest
import net.grinder.scriptengine.groovy.junit.GrinderRunner
import net.grinder.scriptengine.groovy.junit.annotation.BeforeProcess
import net.grinder.scriptengine.groovy.junit.annotation.BeforeThread
import org.junit.Test
import org.junit.runner.RunWith
import org.slf4j.LoggerFactory

import static net.grinder.script.Grinder.grinder
import static org.hamcrest.Matchers.is
import static org.junit.Assert.assertThat

/**
* A simple example using the HTTP plugin that shows the retrieval of a single page via HTTP.
*
* This script is automatically generated by ngrinder.
*
* @author admin
*/
@RunWith(GrinderRunner)
class TestRunner {
    public static GTest test
    public static HTTPRequest request

	@BeforeProcess
	public static void beforeProcess() {
        HTTPPluginControl.getConnectionDefaults().timeout = 6000
        test = new GTest(1, "http://192.168.219.108:8081")
        request = new HTTPRequest()
        test.record(request);
        grinder.logger.info("before process.");
	}

	@BeforeThread
	public void beforeThread() {
        LoggerFactory.getLogger("worker").setLevel(Level.ERROR)
        grinder.statistics.delayReports = true;
        grinder.logger.info("before thread.");
	}
	
	private NVPair[] headers() {
        return [
                new NVPair("Content-type", "application/json;charset=UTF-8")
        ];
    }

	@Test
	public void test(){
		def list = ["qwer123@naver.com", "qwer1234@naver.com", "qwer12345@naver.com"]; //현재 DB에 있는 유저들
		int idx = Math.abs(new Random().nextInt()) % 3;

		/* perfromance가 1 && (seatType가 VIP && seatNumber가 3)인 좌석을 동시에 예매
		{"id":1,"title":"2021 정오의 음악회 5월","startDate":"2021-06-30","email": ~~,"seatType":"VIP","seatNumber":3,"price" : "20,000원"}
		*/
		
		def json = '{"id":1,"title":"2021 정오의 음악회 5월","startDate":"2021-06-30","email":"' + list[idx] + '","seatType":"VIP","seatNumber":1,"price":"20,000원"}';
		
		String reqUrl = "http://192.168.219.108:8081/api/performance/booking";
		
		HTTPResponse result = request.POST(reqUrl, json.getBytes(), headers());
        grinder.logger.info(result.getText());
        grinder.logger.info(result.getHeader("Content-type"));

		if (result.statusCode == 301 || result.statusCode == 302) {
			grinder.logger.warn("Warning. The response may not be correct. The response code was {}.", result.statusCode)
		} else {
			assertThat(result.statusCode, is(200));
		}
	}
}
```
다음과 같이 테스트 스크립트를 작성 후 Validate 하면 500에러를 반환합니다.
```
org.springframework.http.converter.HttpMessageNotReadableException: JSON parse error: Invalid UTF-8 start byte 0xbf; nested exception is com.fasterxml.jackson.databind.JsonMappingException: Invalid UTF-8 start byte 0xbf
 at [Source: (PushbackInputStream); line: 1, column: 26] (through reference chain: comento.backend.ticket.dto.BookingDto["title"])
	at org.springframework.http.converter.json.AbstractJackson2HttpMessageConverter.readJavaType(AbstractJackson2HttpMessageConverter.java:389)
	at org.springframework.http.converter.json.AbstractJackson2HttpMessageConverter.read(AbstractJackson2HttpMessageConverter.java:342)
	at org.springframework.web.servlet.mvc.method.annotation.AbstractMessageConverterMethodArgumentResolver.readWithMessageConverters(AbstractMessageConverterMethodArgumentResolver.java:185)
	at org.springframework.web.servlet.mvc.method.annotation.RequestResponseBodyMethodProcessor.readWithMessageConverters(RequestResponseBodyMethodProcessor.java:160)
	at org.springframework.web.servlet.mvc.method.annotation.RequestResponseBodyMethodProcessor.resolveArgument(RequestResponseBodyMethodProcessor.java:133)
	at org.springframework.web.method.support.HandlerMethodArgumentResolverComposite.resolveArgument(HandlerMethodArgumentResolverComposite.java:121)
	at org.springframework.web.method.support.InvocableHandlerMethod.getMethodArgumentValues(InvocableHandlerMethod.java:170)
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:137)
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:106)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:895)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:808)
	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87)
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1064)
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:963)
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1006)
	at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:909)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:681)
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:883)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:764)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:227)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
	at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:100)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
	at org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:93)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
	at org.springframework.boot.actuate.metrics.web.servlet.WebMvcMetricsFilter.doFilterInternal(WebMvcMetricsFilter.java:96)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:197)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:97)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:542)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:135)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:78)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:357)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:382)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:893)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1726)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191)
	at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.base/java.lang.Thread.run(Thread.java:835)
Caused by: com.fasterxml.jackson.databind.JsonMappingException: Invalid UTF-8 start byte 0xbf
 at [Source: (PushbackInputStream); line: 1, column: 26] (through reference chain: comento.backend.ticket.dto.BookingDto["title"])
	at com.fasterxml.jackson.databind.JsonMappingException.wrapWithPath(JsonMappingException.java:390)
	at com.fasterxml.jackson.databind.JsonMappingException.wrapWithPath(JsonMappingException.java:349)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.wrapAndThrow(BeanDeserializerBase.java:1822)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeWithErrorWrapping(BeanDeserializer.java:567)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeUsingPropertyBased(BeanDeserializer.java:449)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeFromObjectUsingNonDefault(BeanDeserializerBase.java:1405)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:362)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:195)
	at com.fasterxml.jackson.databind.deser.DefaultDeserializationContext.readRootValue(DefaultDeserializationContext.java:322)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4593)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3601)
	at org.springframework.http.converter.json.AbstractJackson2HttpMessageConverter.readJavaType(AbstractJackson2HttpMessageConverter.java:378)
	... 55 common frames omitted
Caused by: com.fasterxml.jackson.core.JsonParseException: Invalid UTF-8 start byte 0xbf
 at [Source: (PushbackInputStream); line: 1, column: 26]
	at com.fasterxml.jackson.core.JsonParser._constructError(JsonParser.java:2337)
	at com.fasterxml.jackson.core.base.ParserMinimalBase._reportError(ParserMinimalBase.java:710)
	at com.fasterxml.jackson.core.json.UTF8StreamJsonParser._reportInvalidInitial(UTF8StreamJsonParser.java:3606)
	at com.fasterxml.jackson.core.json.UTF8StreamJsonParser._reportInvalidChar(UTF8StreamJsonParser.java:3602)
	at com.fasterxml.jackson.core.json.UTF8StreamJsonParser._finishString2(UTF8StreamJsonParser.java:2545)
	at com.fasterxml.jackson.core.json.UTF8StreamJsonParser._finishAndReturnString(UTF8StreamJsonParser.java:2471)
	at com.fasterxml.jackson.core.json.UTF8StreamJsonParser.getText(UTF8StreamJsonParser.java:302)
	at com.fasterxml.jackson.databind.deser.std.StringDeserializer.deserialize(StringDeserializer.java:41)
	at com.fasterxml.jackson.databind.deser.std.StringDeserializer.deserialize(StringDeserializer.java:11)
	at com.fasterxml.jackson.databind.deser.SettableBeanProperty.deserialize(SettableBeanProperty.java:542)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeWithErrorWrapping(BeanDeserializer.java:565)
	... 63 common frames omitted
```
utf-8로 인식하지 못하는 문제인 것 같아 intellj 설정에서 editor-file encodings 에서 global, project, properties에 대해 모두 utf-8로 바꾸었고, run configurations에 java option에 `"-Dfile.encoding=UTF-8"`를 추가했습니다. 
이후에도 안되어서 springbootapplication에 utf-8로 설정하는 코드를 추가했는데도 동일한 에러가 발생합니다 ... 
혹시 원인을 알 수 있을까요?
```java
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.context.annotation.Bean;
import org.springframework.http.converter.HttpMessageConverter;
import org.springframework.http.converter.StringHttpMessageConverter;
import org.springframework.web.filter.CharacterEncodingFilter;

import java.nio.charset.Charset;

@SpringBootApplication
public class TicketApplication {

	public static void main(String[] args) {
		SpringApplication.run(TicketApplication.class, args);
	}

	@Bean
	public HttpMessageConverter<String> responseBodyConverter() {
		return new StringHttpMessageConverter(Charset.forName("UTF-8"));
	}

	@Bean
	public CharacterEncodingFilter  characterEncodingFilter() {
		CharacterEncodingFilter characterEncodingFilter = new CharacterEncodingFilter();
		characterEncodingFilter.setEncoding("UTF-8");
		characterEncodingFilter.setForceEncoding(true);
		return characterEncodingFilter;
	}
}
```

**Comment by comento-yun** [comment]
script생성할때 여기 url은 어떻게 기입하셨나요??

![image](https://user-images.githubusercontent.com/89817180/135945065-6ccbf945-3ddc-4561-ac79-fe560b43df7d.png)

**Comment by hyejungg** [comment]
넵!

**Comment by hyejungg** [comment]
@comento-yun 
`http://192.168.219.108:8081/api/performance/booking`로 기입했습니다!

**Comment by hyejungg** [comment]
@comento-yun
[이 블로그를 참고하여](http://jmlim.github.io/ngrinder/2019/07/01/ngrinder-docker-setup/) json mapping 문제는 해결했습니다!

그러나 email이 null 값으로 전달되어 401 에러가 발생하는 문제를 해결해야 부하테스트를 할 수 있을 것 같습니다.....  (Postman에서는 정상적으로 동작)
테스트코드에서 선언한 list를 읽지 못하는 문제인 것 같은데 groovy에서 아래와 같이 배열을 선언하여 접근하는 방법을 옳지 않은 방법인가요 .. ?
```groovy
static String[] list = ["qwer123@naver.com", "qwer1234@naver.com", "qwer12345@naver.com"];
int idx = Math.abs(new Random().nextInt()) % 3;
list[idx]; //이렇게 접근 불가?!
```

- 테스트코드
```groovy
import HTTPClient.HTTPResponse
import HTTPClient.NVPair
import groovy.json.JsonOutput
import ch.qos.logback.classic.Level
import net.grinder.plugin.http.HTTPPluginControl
import net.grinder.plugin.http.HTTPRequest
import net.grinder.script.GTest
import net.grinder.scriptengine.groovy.junit.GrinderRunner
import net.grinder.scriptengine.groovy.junit.annotation.BeforeProcess
import net.grinder.scriptengine.groovy.junit.annotation.BeforeThread
import org.junit.Before
import org.junit.Test
import org.junit.runner.RunWith
import org.slf4j.LoggerFactory

import static net.grinder.script.Grinder.grinder
import static org.hamcrest.Matchers.is
import static org.junit.Assert.assertThat

/**
* A simple example using the HTTP plugin that shows the retrieval of a single page via HTTP.
*
* This script is automatically generated by ngrinder.
*
* @author admin
*/
@RunWith(GrinderRunner)
class TestRunner {
    public static GTest test
    public static HTTPRequest request
    public static NVPair[] headers = []

    static String[] list = ["qwer123@naver.com", "qwer1234@naver.com", "qwer12345@naver.com"];
    static String url = "http://ip주소:서버포트"
    static String commonPath = "/api/performance/booking"

    static String postUrl = url + commonPath;

	@BeforeProcess
	public static void beforeProcess() {
        HTTPPluginControl.getConnectionDefaults().timeout = 6000
        test = new GTest(1, url)
        request = new HTTPRequest()
        test.record(request);

        // Set header datas
        List<NVPair> headerList = new ArrayList<NVPair>()
        headerList.add(new NVPair("Content-Type", "application/json;charset=UTF-8"))
        
        headers = headerList.toArray()
        grinder.logger.info("before process.");
	}

	@BeforeThread
	public void beforeThread() {
        LoggerFactory.getLogger("worker").setLevel(Level.ERROR)
        grinder.statistics.delayReports = true;
        grinder.logger.info("before thread.");
	}

    @Before
    void before() {
        request.setHeaders(headers)
        grinder.logger.info("before thread. init headers");
    }
	

	@Test
	public void test(){
        testPost();
	}
    
    void testPost(){
        /* perfromance가 1 && (seatType가 VIP && seatNumber가 3)인 좌석을 동시에 예매
		{"id":1,"title":"2021 정오의 음악회 5월","startDate":"2021-06-30","email": ~~,"seatType":"VIP","seatNumber":3,"price" : "20,000원"}
		*/
		int idx = Math.abs(new Random().nextInt()) % 3;

        Map<String, Object> paramData = new HashMap<>();
        List<Map<String, Object>> items = new ArrayList<>();
        Map<String, Object> item = new HashMap<>();
        item.put("id", 1);
        item.put("title", "2021 정오의 음악회 5월");
        item.put("startDate", "2021-06-30");
        item.put("email", list[idx]);
        item.put("seatType", "VIP");
        item.put("seatNumber", 3);
        item.put("price", "20,000원");
        items.add(item);
        paramData.put("items", items);

        
        String json = JsonOutput.toJson(paramData);
        HTTPResponse result = request.POST(postUrl, json.getBytes())
        resultCheck(result)
		
        grinder.logger.info(result.getText());
        grinder.logger.info(result.getHeader("Content-type"));
    }

    void resultCheck(result) {
        if (result.statusCode == 301 || result.statusCode == 302) {
            grinder.logger.warn("Warning. The response may not be correct. The response code was {}.", result.statusCode);
        } else {
            assertThat(result.statusCode, is(200));
        }
    }
}
```

**Comment by comento-yun** [comment]
@hyejungg  
바쁜일이 있어서 답변이 늦었습니다.
두번째 스크립트는 디버깅 찍어보면 전부다 null로 넘어가고 첫번째 스크립트에서 json.getBytes할때 `json.getBytes("UTF-8")` 하면 json parsing error없이 넘어가요~ 첫번째 스크립트에서 작성하신 list에서 랜덤으로 이메일 추출하는로직에는 문제가 없구요!

![image](https://user-images.githubusercontent.com/89817180/136025485-c5077c39-2657-4068-9fcf-a3fde1496d08.png)


```groovy

import HTTPClient.HTTPResponse
import HTTPClient.NVPair
import ch.qos.logback.classic.Level
import net.grinder.plugin.http.HTTPPluginControl
import net.grinder.plugin.http.HTTPRequest
import net.grinder.script.GTest
import net.grinder.scriptengine.groovy.junit.GrinderRunner
import net.grinder.scriptengine.groovy.junit.annotation.BeforeProcess
import net.grinder.scriptengine.groovy.junit.annotation.BeforeThread
import org.junit.Test
import org.junit.runner.RunWith
import org.slf4j.LoggerFactory

import static net.grinder.script.Grinder.grinder
import static org.hamcrest.Matchers.is
import static org.junit.Assert.assertThat

/**
* A simple example using the HTTP plugin that shows the retrieval of a single page via HTTP.
*
* This script is automatically generated by ngrinder.
*
* @author admin
*/
@RunWith(GrinderRunner)
class TestRunner {
    public static GTest test
    public static HTTPRequest request

	@BeforeProcess
	public static void beforeProcess() {
        HTTPPluginControl.getConnectionDefaults().timeout = 6000
        test = new GTest(1, "http://192.168.219.109:9081")
        request = new HTTPRequest()
        test.record(request);
        grinder.logger.info("before process.");
	}

	@BeforeThread
	public void beforeThread() {
        LoggerFactory.getLogger("worker").setLevel(Level.ERROR)
        grinder.statistics.delayReports = true;
        grinder.logger.info("before thread.");
	}
	
	private NVPair[] headers() {
        return [
                new NVPair("Content-type", "application/json;charset=UTF-8")
        ];
    }

	@Test
	public void test(){
		def list = ["qwer123@naver.com", "qwer1234@naver.com", "qwer12345@naver.com"]; //현재 DB에 있는 유저들
		int idx = Math.abs(new Random().nextInt()) % 3;

		/* perfromance가 1 && (seatType가 VIP && seatNumber가 3)인 좌석을 동시에 예매
		{"id":1,"title":"2021 정오의 음악회 5월","startDate":"2021-06-30","email": ~~,"seatType":"VIP","seatNumber":3,"price" : "20,000원"}
		*/
		
		def json = '{"id":1,"title":"2021 정오의 음악회 5월","startDate":"2021-06-30","email":"' + list[idx] + '","seatType":"VIP","seatNumber":1,"price":"20,000원"}';
		
		String reqUrl = "http://192.168.219.109:9001/api/performance/booking";
		
		HTTPResponse result = request.POST(reqUrl,json.getBytes("UTF-8"), headers());
        grinder.logger.info(result.getText());
        grinder.logger.info(result.getHeader("Content-type"));

		if (result.statusCode == 301 || result.statusCode == 302) {
			grinder.logger.warn("Warning. The response may not be correct. The response code was {}.", result.statusCode)
		} else {
			assertThat(result.statusCode, is(200));
		}
	}
}

```

**Comment by hyejungg** [comment]
감사합니다!
